wandb_version: 1

model name:
  desc: null
  value: __main__.Resnet_plus_LSTM
run name:
  desc: null
  value: resnet18+LSTM_hid=64
epochs:
  desc: null
  value: 100
learning rate:
  desc: null
  value: 0.0001
optimizer:
  desc: null
  value: Adam
uses scheduler:
  desc: null
  value: true
min_lr:
  desc: null
  value: 5.0e-05
lr_steps:
  desc: null
  value: 1000
num_classes:
  desc: null
  value: 7
hid_size:
  desc: null
  value: 64
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.5
    framework: huggingface
    huggingface_version: 4.32.1
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1712507300.0
    t:
      1:
      - 1
      - 5
      - 11
      - 41
      - 49
      - 53
      - 55
      - 80
      3:
      - 13
      - 16
      - 23
      4: 3.11.5
      5: 0.16.5
      6: 4.32.1
      8:
      - 1
      - 2
      - 3
      - 5
      13: windows-amd64
