wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1712526801.0
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.11.5
      5: 0.16.5
      8:
      - 1
      - 2
      - 3
      - 5
      13: windows-amd64
